### ISSUE TITLE
Adding form validation in contact page

### ISSUE THREAD

**Issue by 435akashjha** [chiraag-kakar/sharenlearn#111]
In the contact form there is no validation of email and text area and therefore anyone spam

**Comment by 435akashjha** [comment]
Since I am beginner at the open source I want to work on this issue.

**Comment by arpit456jain** [comment]
@harshita2216  mam i am a gssoc'21 participant and i want to add some form validation in contact page because I think there are no validations in it as i am able to fill all fields by 'a' and it got submitted successfully and some flash message feature using message framework in Django Kindly Assign me this issue I will do this as soon as possible.

**Comment by arpit456jain** [comment]
Thank you mam will start work on it as soon as possible

**Comment by arpit456jain** [comment]
@harshita2216  mam I had solved this issue may i create a PR.

**Comment by arpit456jain** [comment]
@harshita2216 mam Please Review my PR.

**Comment by arpit456jain** [comment]
@chiraag-kakar sir please review my PR.

**Comment by Aryamanz29** [comment]
@chiraag-kakar  @harshita2216  Any response??? regarding this issue.

**Comment by Aryamanz29** [comment]
> @chiraag-kakar sir please review my PR.

This is really bad, Why project maintainer not reviewing participants PR

**Comment by arpit456jain** [comment]
@harshita2216 please close this issue as my PR was got merged .
I had not opened this issue that's why i can't close it from my side
