### ISSUE TITLE
add myvenv in .gitignore file

### ISSUE THREAD

**Issue by flyingsonu122** [chiraag-kakar/sharenlearn#98]
add this so that local files of **virtual environment** in not uploaded to GitHub

this is very much required see size here

![image](https://user-images.githubusercontent.com/51280276/111266379-7ac26d00-8650-11eb-9c32-0a304d6d4472.png)

**Comment by flyingsonu122** [comment]
@chiraag-kakar @harshita2216 @amanjha8100 please assign this to me

**Comment by amanjha8100** [comment]
Ok, is this a issue, different people may choose to name virtual environment's differently. I name them as vir, Project Admin probably names them as virtual, which he has included in his .gitignore , you may choose to name them as myvenv. Everyone while setting up this project should take care of this issue by themselves. Otherwise we would have to add a lot of names n .gitignore.

**Comment by flyingsonu122** [comment]
You have written a guide on readme.md about that

**Comment by flyingsonu122** [comment]
Or else you can write there to include the created virtual name in .gitignore file
